#Artifact Registry - create repository kmtestrepo
#build and push to repository kmtestrepo
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}', '.' ]

images:
- '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}'
 
substitutions:
  _LOCATION: "us-east1"
  _REPOSITORY: "kmtestrepo"
  _IMAGE: "my-image"
